spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/atcdb}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: atc-group
      auto-offset-reset: earliest