apiVersion: apps/v1
kind: Deployment
metadata:
  name: atc-backend
  labels:
    app: atc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atc-backend

  template:
    metadata:
      labels:
        app: atc-backend

    spec:
      containers:
        - name: atc-backend
          image: atc-event-monitor-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo:27017/atcdb"

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

          # 🔥 IMPORTANT (simple health checks = looks professional)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5